services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: nestjs-mysql
      NODE_ENV: production
      DB_PORT: 3306
    depends_on:
      - mysql
    volumes:
      - /var/log/nestjs:/app/logs

  mysql:
    image: mysql:8.0
    container_name: nestjs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: nestjs-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: