services:
  mysql:
    image: mysql:8.0
    container_name: nestjs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: nestjs-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: nestjs-meilisearch
    restart: always
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - meilisearch_data:/meili_data

volumes:
  mysql_data:
  meilisearch_data: