version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: mysql-container
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: